name: msbuildtest


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: testenvironment
    steps:
     - uses: actions/checkout@v2
     - name: install msbuild.exe
       uses: microsoft/setup-msbuild@v1

     - name: Run msbuild.exe
       run: msbuild.exe
